[versions]
agp = "9.0.1"
kgp = "2.2.10"
rerune = "0.4.1"
composeBom = "2024.06.00"
activityCompose = "1.9.1"
lifecycle = "2.8.4"
appcompat = "1.7.0"
coreKtx = "1.13.1"
swipeRefresh = "1.1.0"
material = "1.12.0"

[libraries]
rerune-compose = { module = "io.rerune:rerune-android-compose", version.ref = "rerune" }
rerune-views = { module = "io.rerune:rerune-android-views", version.ref = "rerune" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
swipe-refresh-layout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefresh" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kgp" }
